[package]
name = "test2"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "7.0.0"
tokio = { version = "1.0", features = ["full"] }
walkdir = "2.3.3"
chrono = "0.4"
async_ftp = { version = "6.0.0", features = ["secure"] }